#!/bin/bash

flex calc-lexico.l 
bison -d calc-sintaxis.y
gcc lex.yy.c calc-sintaxis.tab.c

mv lex.yy.c script_generated/lex.yy.c
mv calc-sintaxis.tab.c script_generated/calc-sintaxis.tab.c
mv calc-sintaxis.tab.h script_generated/calc-sintaxis.tab.h
mv a.out script_generated/a.out

declare -i file_number=1
for file in ../test/resources/acceptedPrograms/*; do
    printf "\n\nValid program $file_number:\n";
    ./script_generated/a.out $file
    file_number=file_number+1
done

file_number=1
for file in ../test/resources/invalidPrograms/*; do
    printf "\n\nInvalid program $file_number:\n";
    ./script_generated/a.out $file
    file_number=file_number+1
done
