#ifndef ENUMERATION_H
#define ENUMERATION_H

typedef enum {TYPEINT, TYPEBOOL, UNDEFINED, TYPEVOID} types;


typedef enum {METHOD, EXTERNMETHOD, CONST, VAR, TYPELESS, NEXT, RETURN, METHODCALL} identifierType;

#endif